
module.exports = Object.freeze({
    MODAL_BODY_TYPES: {
        USER_DETAIL: "USER_DETAIL",
        PRODUCT_ADD_NEW: "PRODUCT_ADD_NEW",
        EXPENSE_ADD_NEW: "EXPENSE_ADD_NEW",
        CONFIRMATION: "CONFIRMATION",
        DEFAULT: "",
    },

    RIGHT_DRAWER_TYPES: {
        NOTIFICATION: "NOTIFICATION",
        CALENDAR_EVENTS: "CALENDAR_EVENTS",
    },

    CONFIRMATION_MODAL_CLOSE_TYPES: {
        PRODUCT_DELETE: "PRODUCT_DELETE",
        EXPENSE_DELETE: "EXPENSE_DELETE"
    },

    MESSAGE_API: {
        DELETED_SUCCESS: "DELETED_SUCCESS"
    },
    CURRENT_FORMAT: {
        VND: 'vi-VN'
    },
    FORMAT_DATE: {
        MONTH_YEAR: 'MMM-yyyy'
    }
});
